name: Test Deployment

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test-deployment:
    name: Test Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl

      - name: Make script executable
        run: chmod +x scripts/test_deployment.sh

      - name: Run deployment tests
        env:
          CI: true
          WAIT_TIMEOUT: 120 # Increase timeout for CI environment
          CURL_TIMEOUT: 30 # Increase curl timeout for CI environment
        run: ./scripts/test_deployment.sh --cleanup

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: docker-logs
          path: |
            docker-compose.log
            ./*.log
          retention-days: 5
